### ISSUE TITLE
Move to JuliaParallel

### ISSUE THREAD

**Issue by jakebolewski** [JuliaParallel/PETSc.jl#1]
Hi Jared,

Would you consider moving this repository to the JuliaParallel organization?  I can send you an invite to join the organization so you can have push access.  It would be great to give your work more visibility and prevent duplication of effort.  A PETSc interface has been on wishlist for parallel Julia for a long time.  I think now is the right time to start working towards this goal now that we will start to have package precompilation so load times won't be intolerable.

What do you think?

**Comment by JaredCrean2** [comment]
Sounds like a good idea.

**Comment by andreasnoack** [comment]
Any updates on this? It will make it slightly easier for us to open PRs and probably also give a little omre visibility.

**Comment by jakebolewski** [comment]
Bump @JaredCrean2. It is ok that the package is WIP.

**Comment by JaredCrean2** [comment]
What do I need to do?  I'm not familiar with how the umbrella organizations work?

**Comment by jakebolewski** [comment]
Join the JuliaParallel organization (if you have not already).  Then click on the "settings" tab in the right hand panel for the github Petsc.jl page.  You should see the transfer ownership option at the bottom of the settings page.

**Comment by JaredCrean2** [comment]
How do I join the organization?  For other organizations I got added by the organization admins.

**Comment by jiahao** [comment]
I just sent an invitation
