### ISSUE TITLE
Why protect finalize with `comm == MPI.COMM_SELF`?

### ISSUE THREAD

**Issue by jkozdon** [JuliaParallel/PETSc.jl#114]
Why are these needed?

https://github.com/JuliaParallel/PETSc.jl/blob/1c534aee0fb91f0c067fc05ca64b12e2dc2f7944/src/ksp.jl#L34-L36 
https://github.com/JuliaParallel/PETSc.jl/blob/6f68f083431afb52cd3d369ad1b35bcbedd0598a/src/snes.jl#L61-L63

cc: @simonbyrne @thomasgibson

**Comment by simonbyrne** [comment]
The main issue is that the PETSc `destroy` functions need to be called collectively over the communicator, and this can't be guaranteed with the GC.

**Comment by jkozdon** [comment]
This makes sense.

So for MPI jobs the user should call destroy manually then (if it really matters for an application)?

**Comment by simonbyrne** [comment]
Yes that was the idea, but we hadn't added any MPI functions yet!

**Comment by jkozdon** [comment]
No problem. I'm trying to build out some of the functionality for something I want to try, so I can add what I need and get it working.
