### ISSUE TITLE
maintainer / owner?

### ISSUE THREAD

**Issue by jkozdon** [JuliaParallel/PETSc.jl#116]
I was wondering who the maintainer / owner is of `PETSc.jl`? I'm looking to use it for a project I'm starting, and I am happy to help / take over if no one is actively doing this (as seems to be the case).

**Comment by boriskaus** [comment]
I am wondering that as well; in any case it seems there is only sporadic activity in the development of this package which is a pity as PETSc is indeed a very powerful package to write (implicit) parallel codes. So having a working version would likely result in more people switching to Julia altogether. 

We are at least planning to tackle some of the issues mentioned in #109 and create a PR for that from our forked branch. Perhaps it's a good idea to combine efforts to ensure that we don't duplicate work.

**Comment by boriskaus** [comment]
@jkozdon I can see that it is probably easier to start with a clean repo. 
Yet, I hope this will be pushed back to PETSc.jl ultimately, as this is the place where most people will be looking for it. There are already several packages around that do part of the same functionality (with different flavors). It's probably better to focus the development efforts on one, better maintained, package.

Yes, would be great to have a video chat about this (send me a mail). Ideally, some on the PETSc development team would have a look at this as well, so perhaps @psanan, @knepley, or @jedbrown can chime in.

**Comment by jkozdon** [comment]
> Yet, I hope this will be pushed back to PETSc.jl ultimately, as this is the place where most people will be looking for it.

That's my thought, but also didn't want to be roadblocked in what I wanted to do. Also knew that fixing things would break lots of stuff.

> Yes, would be great to have a video chat about this (send me a mail).

Will do.

**Comment by jkozdon** [comment]
@simonbyrne Any chance you can give @boriskaus and me owner privileges.

**Comment by simonbyrne** [comment]
Sorry, I wasn't actually subscribed to notifications. You should both now have maintainer access, let me know if further permissions are required.

Do feel free to make changes as you see fit. It hasn't been a registered package since v1.0, so there are no real concerns about breaking changes!

**Comment by psanan** [comment]
@jkozdon @boriskaus @simonbyrne  I've been lurking so far but I also see a lot of value in improving this package. Definitely interested to join a call.
