### ISSUE TITLE
Fix deprecations

### ISSUE THREAD

**Issue by andreasnoack** [JuliaParallel/PETSc.jl#12]
When loading PETSc on 0.4 there are quite few deprecation warnings. If 0.3 will remain a target for the package `Compat.jl` should be added as a depedency and the syntax updates should have a `@compat` (I like to put them where the line starts).

**Comment by jiahao** [comment]
I fixed some of the deprecated syntax in #17 in `src/*.jl`, explicitly breaking 0.3 compatibility. I haven't touched the generated wrappers

**Comment by stevengj** [comment]
There currently seem to be no deprecation warnings (except for FactCheck).
