### ISSUE TITLE
PETSc options treatment

### ISSUE THREAD

**Issue by jkozdon** [JuliaParallel/PETSc.jl#144]
The way the library is currently written the PETSc options are not universally set, but turned on and off for different operations.

I don't know enough about PETSc, but is this a good design decision? Is it possible that the options won't carry through properly when we need them?

For example https://github.com/JuliaParallel/PETSc.jl/blob/38552bae828b4a6141895e6486b51e1e82f1cc61/src/snes.jl#L48-L62

Is this mainly needed when things are created?

@boriskaus or @psanan you have any thoughts?

My inclination right now is to leave it as is, but wanted to start a discussion in case this became important  or a problem.

**Comment by boriskaus** [comment]
I think this is consistent with the way it is usually done in PETSc. There is a general options database to which command-line options are added. If you want specific options for a KSP or SNES object, you need to activate that for this option.
What is important to have in practice is the ability to add a prefix for a certain KSP; this way you can set different solvers for different equations (e.g., direct solvers for temperature diffusion and multigrid solvers for Stokes).


On 14. Jul 2021, at 04:27, Jeremy E Kozdon ***@***.***> wrote:

﻿

The way the library is currently written the PETSc options are not universally set, but turned on and off for different operations.

I don't know enough about PETSc, but is this a good design decision? Is it possible that the options won't carry through properly when we need them?

For example https://github.com/JuliaParallel/PETSc.jl/blob/38552bae828b4a6141895e6486b51e1e82f1cc61/src/snes.jl#L48-L62

Is this mainly needed when things are created?

@boriskaus<https://github.com/boriskaus> or @psanan<https://github.com/psanan> you have any thoughts?

My inclination right now is to leave it as is, but wanted to start a discussion in case this became important or a problem.

**Comment by psanan** [comment]
Right - the "options database" is a key-value store which is used to set up solvers, as @boriskaus says, and can also be directly used by the user if they want to define their own command line options. In normal usage there is a single (formerly global) options database that's used for everything, but there can be multiple ones.
