### ISSUE TITLE
more types?

### ISSUE THREAD

**Issue by jkozdon** [JuliaParallel/PETSc.jl#145]
Should we have more types, for example:

- `LocalVec` and `GlobalVec`?
- `DMDA` and `DMStag` and `DMXXX`?

PETSc doesn't really distinguish between these, but we could leverage the Julia type system to make sure that the right functions are called always. (Not sure how to handle cases when we do not necessarily know the type, such as what's returned from `DMGetCoordinateDM`.)

**Comment by simonbyrne** [comment]
It does have different Vec types (see https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/VecType.html#VecType), but it's a bit more dynamic than Julia (e.g. you can [modify the type](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/VecSetType.html) of an existing Vec)

I think the main question is whether the distinction is useful from a dispatch perspective. In particular, I had originally planned that `VecSeq` objects would have finalizers, but not the MPI ones (though that could be handled differently).

**Comment by jkozdon** [comment]
Right. I meant mainly from the dispatch perspective.

For instance, the function [`DMGlobalToLocal`](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DM/DMGlobalToLocal.html) takes two `Vec`s, but really one should be a "local" vector and one a "global" vector. This could be tracked with the type system in Julia.

What I meant by "PETSc doesn't really distinguish between these " I meat at the C-types level. For instance everything is really just a  [`Vec`](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/Vec.html#Vec), though the types can be queried at runtime through the [`VecGetType`](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/VecGetType.html#VecGetType).

I'm also not sure that you can really change a vector in PETSc once it's been setup, this is mainly for initialization. My read o the [code](https://www.mcs.anl.gov/petsc/petsc-current/src/vec/vec/interface/vecreg.c.html#VecSetType) is that if you call `VecSetType` on an existing vector, you first destroy the data then create a new one (data is not preserved through `VecSetType`)

**Comment by psanan** [comment]
The way it enforces that things are the correct size wrt being local or global is that it the `DM` contains a `VecScatter` object which defines the local-global mapping, and (in debug mode only!) it'll check that the `Vec`s passed as arguments are the expected local and global sizes, which are calculated during `DMSetup()`. Here's the actual check in [https://petsc.org/release/src/vec/is/sf/interface/vscat.c.html#VecScatterBegin](the source for `VecScatterBegin).

**Comment by jkozdon** [comment]
Right. I was wondering if there would be any benefit to having any checks at compile time (obviously some stuff can only be checked at run time such as whether you can actually scatter between two vectors). But some sanity checks might be possible at run time, but maybe it's not worth it for now.

For example, I was thinking that [`DMCreateGlobalVector`](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DM/DMCreateGlobalVector.html#DMCreateGlobalVector) and [`DMCreateLocalVector`](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/DM/DMCreateLocalVector.html#DMCreateLocalVector) could return different types, they would still be `AbstractVec` subtypes and usable anywhere a `Vec` could be used, but also would allow for making sure that the right vecs get passed into  `DMGlobalToLocal`

**Comment by jkozdon** [comment]
Probably worth waiting until we have more concrete use cases.
