### ISSUE TITLE
ERROR: Method overwriting is not permitted during Module precompilation

### ISSUE THREAD

**Issue by ZhangFengshun** [JuliaParallel/PETSc.jl#188]
julia> using PETSc
Precompiling PETSc
        Info Given PETSc was explicitly requested, output will be shown live
WARNING: Method definition localsize(Ptr{Nothing}) in module PETSc at /home/zfs/.julia/packages/PETSc/4khzV/src/vec.jl:155 overwritten on the same line (check for duplicate calls to `include`).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
  ? PETSc
[ Info: Precompiling PETSc [ace2c81b-2b5f-4b1e-a30d-d662738edfe0]
WARNING: Method definition localsize(Ptr{Nothing}) in module PETSc at /home/zfs/.julia/packages/PETSc/4khzV/src/vec.jl:155 overwritten on the same line (check for duplicate calls to `include`).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
[ Info: Skipping precompilation since __precompile__(false). Importing PETSc [ace2c81b-2b5f-4b1e-a30d-d662738edfe0].

julia>

**Comment by boriskaus** [comment]
As I wrote on an earlier issue, `PETSc.jl` is currently broken and I have no time to finish or bring it up to date (`PETSc_jll` is already enough of a time sink).
So if you or anyone else is willing to bring the package up to speed I am happy to give you a bit more info.

**Comment by ViralBShah** [comment]
For now we should start by disabling precompliation. This should be a simple PR, and it would be great to get more contributions to maintaining this package.

**Comment by ViralBShah** [comment]
Also fixed on `main`. Please dev the package and try it out. We can close this after tagging a new version.
