### ISSUE TITLE
ERROR install PETSc.jl

### ISSUE THREAD

**Issue by weapon-dog** [JuliaParallel/PETSc.jl#189]
My version of Julia is the latest, and after experiments on both Windows and Ubuntu 22.04 systems, I found that when I used add PETSc to install PETSc.jl, the following error occurred:
 Info Given PETSc was explicitly requested, output will be shown live
WARNING: Method definition (::Type{PETSc.DMBoundaryType})(Integer) in module PETSc at Enums.jl:210 overwritten on the same line (check for duplicate calls to `include`).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
  ? PETSc
  1 dependency successfully precompiled in 3 seconds. 19 already precompiled.
  1 dependency failed but may be precompilable after restarting julia
  1 dependency had output during precompilation:
┌ PETSc
│  [Output was shown above]
└
[ Info: Precompiling PETSc [ace2c81b-2b5f-4b1e-a30d-d662738edfe0]
WARNING: Method definition (::Type{PETSc.DMBoundaryType})(Integer) in module PETSc at Enums.jl:210 overwritten on the same line (check for duplicate calls to `include`).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
[ Info: Skipping precompilation since __precompile__(false). Importing PETSc [ace2c81b-2b5f-4b1e-a30d-d662738edfe0].
┌ Warning: Replacing docs for `PETSc.update! :: Tuple{PETSc.DMGlobalVec, Ptr{Nothing}, PETSc.InsertMode}` in module `PETSc`
└ @ Base.Docs docs\Docs.jl:243
┌ Warning: Replacing docs for `PETSc.DMStagVecGetArray :: Union{}` in module `PETSc`
└ @ Base.Docs docs\Docs.jl:243
┌ Warning: Replacing docs for `PETSc.DMStagVecSetValuesStencil :: Union{}` in module `PETSc`
└ @ Base.Docs docs\Docs.jl:243
┌ Warning: Replacing docs for `PETSc.DMStagVecGetValuesStencil :: Union{}` in module `PETSc`
└ @ Base.Docs docs\Docs.jl:243
┌ Warning: Replacing docs for `PETSc.DMStagMatGetValuesStencil :: Union{}` in module `PETSc`
└ @ Base.Docs docs\Docs.jl:243
┌ Warning: Replacing docs for `PETSc.DMStagMatSetValuesStencil :: Union{}` in module `PETSc`
└ @ Base.Docs docs\Docs.jl:243
ERROR: LoadError: ccall method definition: argument 1 type doesn't correspond to a C type
Stacktrace:
  [1] top-level scope
    @ D:\Julia\packages\PETSc\LSdRz\src\ksp.jl:199
  [2] eval(m::Module, e::Any)
    @ Core .\boot.jl:385
  [3] macro expansion
    @ D:\Julia\packages\PETSc\LSdRz\src\lib.jl:120 [inlined]
  [4] top-level scope
    @ D:\Julia\packages\PETSc\LSdRz\src\ksp.jl:108
  [5] include(mod::Module, _path::String)
    @ Base .\Base.jl:495
  [6] include(x::String)
    @ PETSc D:\Julia\packages\PETSc\LSdRz\src\PETSc.jl:1
  [7] top-level scope
    @ D:\Julia\packages\PETSc\LSdRz\src\PETSc.jl:34
  [8] include(mod::Module, _path::String)
    @ Base .\Base.jl:495
  [9] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:2014
 [10] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1812
 [11] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [12] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [13] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1803
 [14] macro expansion
    @ .\loading.jl:1790 [inlined]
 [15] macro expansion
    @ .\lock.jl:267 [inlined]
 [16] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1753
 [17] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [18] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [19] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1746
in expression starting at D:\Julia\packages\PETSc\LSdRz\src\ksp.jl:71
in expression starting at D:\Julia\packages\PETSc\LSdRz\src\PETSc.jl:1

**Comment by boriskaus** [comment]
`PETSc.jl` is currently broken - you at every welcome to help
Fix it.

**Comment by ViralBShah** [comment]
I'm getting the same error as well.

**Comment by ViralBShah** [comment]
Dup of #188
