### ISSUE TITLE
Tagging a new release of PETSc.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/PETSc.jl#197]
@boriskaus Do you understand why PETSc_jll is holding back MPICH_jll to an older version? Should we rebuild the JLL?

```
(PETSc) pkg> status --outdated -m
Project PETSc v0.2.0
Status `~/.julia/dev/PETSc/Manifest.toml`
⌅ [7cb0a576] MPICH_jll v4.1.2+1 (<v4.2.3+0): PETSc_jll
```

**Comment by boriskaus** [comment]
yes that is because I pinned the version of `MPICH_jll` when compiling `PETSc_jll` 3.21.5. `PETSc_jll` 3.22 will not have this issue anymore, once the remaining broken architectures are fixed.

**Comment by ViralBShah** [comment]
I feel that it should be ok to tag a new release of this package. Thoughts?

**Comment by ViralBShah** [comment]
Except for fixing the tests marked as FIXME, the major other thing is getting the documentation generation running again. I still think it should be ok to release a new version of this package that works.

**Comment by boriskaus** [comment]
yes, feel free to release a new version

**Comment by ViralBShah** [comment]
https://github.com/JuliaRegistries/General/pull/117399
