### ISSUE TITLE
missing one(::Mat)

### ISSUE THREAD

**Issue by stevengj** [JuliaParallel/PETSc.jl#47]
Currently this works but produces a dense matrix.

**Comment by kshyatt** [comment]
Is the right thing to do here use [MatDuplicate](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatDuplicate.html#MatDuplicate) and then [MatSetValues](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatSetValues.html#MatSetValues) or is there a better/easier way?

**Comment by stevengj** [comment]
I don't think we want to duplicate the nonzero structure, so maybe just allocate a fresh matrix rather than calling `similar`.

**Comment by kshyatt** [comment]
Wait - do you want `ones(M)`, or `eye(M)`? I thought `ones` preserved the non-zero structure but set all values to `one(T)`?

**Comment by stevengj** [comment]
I want `one(M) = eye(M)`, not `ones(M)`.

**Comment by stevengj** [comment]
I should also mention `diag(M)` and `diagm(v)` via `MatDiagonalSet`/`Get`, while it is on my mind.

**Comment by kshyatt** [comment]
Aha! Then in that case, I agree that MatDuplicate isn't at all what we want :). I think I wrapped `diag(M)` using `MatDiagonalGet` but I didn't do `diagm`.

**Comment by stevengj** [comment]
`ones(M)` does not preserve the non-zero structure, it just makes a matrix of all 1's.  I don't think it is particularly useful.

**Comment by kshyatt** [comment]
Oh god, I was confused between `one` and `ones`.

**Comment by stevengj** [comment]
Hmm, looks like `ones(M::Mat)` gives garbage.
