### ISSUE TITLE
switch to TestNext

### ISSUE THREAD

**Issue by stevengj** [JuliaParallel/PETSc.jl#49]
I'd greatly prefer using `Base.Test` to FactCheck.  With the 0.5 version of Base.Test, we can group tests and report the number passing/failing, just like FactCheck, and with Julia 0.4 we can use https://github.com/IainNZ/BaseTestNext.jl to get the same syntax.

In general, I find our current tests a little messy, verbose, and hard to read.  We have a lot of stuff like this:
```
for i=1:3, j=1:3
  @fact mat6[i,j] --> mat6j[i,j]
end
```
whereas I'd prefer to just do:
```
@test mat6 == mat6j
```
or better yet
```
@test someoperation(Mat(M)) == someoperation(M)
```
where `M` is a Julia test matrix (or `≈` if we expect only approximate equality), so we don't have zillions of `matXXX` temporaries and the test is concise.

We should add constructors and comparison operations as needed to make the tests concise, rather than copying the same verbose code for every test.  If we can't write tests as concise as the corresponding test for a native Julia matrix, that's a good indication that we need more methods.

So changing to Base.Test/TestNext would also be a good excuse to go through the tests and clean them up.

**Comment by kshyatt** [comment]
I agree. You can see in the tests that to test `==` for `Vec` and `Mat` I did something really ugly and bad.

**Comment by kshyatt** [comment]
Has this been resolved?
