### ISSUE TITLE
Additional PETSc build options

### ISSUE THREAD

**Issue by kshyatt** [JuliaParallel/PETSc.jl#55]
In my research, I use MUMPS a lot through PETSc & SLEPc to do eigensolving. Other people use SuperLU or some of the other things PETSc can download and install for you. It might be nice to have a build option that maps to `--download-mumps` or something.

**Comment by psanan** [comment]
There are already two MUMPS.jl packages, and there are (or will be) standalone Julia packages for others of the (many) packages that PETSc can download for you. Should/can one reuse libraries built by those packages in any practical way?

Would a more general (experts-only) approach of allowing the user to directly specify PETSc `configure` flags be an option? 

This a question that I wouldn't have to ask if I was more informed about this project, but once you have configured with the external package, how would you invoke it? Is there an interface to directly set PETSc options database entries?

**Comment by stevengj** [comment]
@psanan, yes, there are interfaces to directly set PETSc options database entries.  You can just use `OPTIONS[:ksp_type]="gmres"` to do `-ksp_type=gmres` globally, and you can also set options when you create the solver object by e.g. `KSP(A, ksp_type="gmres")`.  Sorry about the lack of documentation (#57).

I'm skeptical that people should be specifying our PETSc configure flags.  My first inclination is that we should support two possibilities:

* Build PETSc with as good a set of default options as we can devise.  If it is reasonably reliable, we should include as many free sparse-direct packages (MUMPS, PaStiX, etc?) as we can.

* Allow the build to use external PETSc libraries instead (e.g. the distro packages on Ubuntu), e.g. via `ENV["JULIA_PETSC_DOUBLE"]=/path/to/libpetsc`.  The user can then build with whatever options she wants.  (For any precisions where an external library is not specified, we would fallback to our own PETSc build.)  Shared-library dependencies might get tricky here.

**Comment by kshyatt** [comment]
You can tell PETSc to use an external solver for certain steps (preconditioning, etc) in the command line options. `-st_pc_factor_mat_solver_package mumps` (that's a SLEPc version but the idea is the same). There's an API function for it too.

**Comment by kshyatt** [comment]
Sorry! I pressed the wrong button.

**Comment by psanan** [comment]
Allowing the user the option to specify his or her own existing PETSc build sounds like a better idea that passing flags to the the build process for PETSc.jl. It covers the same case I was concerned about (someone who already has PETSc configured as they like but wants to call it from Julia), and allows this package to concentrate on a single set of configure options. 

Re choosing a standard set of external packages, external linear solvers are clear first candidates, but the size and build time of up to three copies of MUMPS, SuperLU, Pastix, Pardiso, ML, Hypre, Elemental, etc. and their dependencies ([Par]Metis,Scalapack,.. ) could become nontrivial.

**Comment by JaredCrean2** [comment]
> Allowing the user the option to specify his or her own existing PETSc build sounds like a better idea that passing flags to the the build process for PETSc.jl

Why pick just one when you can do both.  See the PR above.

**Comment by JaredCrean2** [comment]
Closed via #69
