### ISSUE TITLE
Local or Global Sizing

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaParallel/PETSc.jl#56]
For a number of the functions that set the sizes of vector and matrices, PETSc lets us either set the local size on each processor (and it figures out the global size), or lets us set the global size and figure out the local partitioning itself.  Currently the `resize!` function for matrices and vectors have the global size as a positional argument and the local size as a keyword argument, but I think we should do the opposite.  I think it is much easier to write codes that keep track of the local size and let PETSc figure out the global sizing.

The other place where this issue comes up is the `length` function.  Is the "length" of a distributed vector the local length or the global length?  I'm in favor of the local length  because I think it will (eventually) lead to better interoperability with functions written for non-distributed arrays?

**Comment by psanan** [comment]
I haven't been following your development here as closely as I'd hoped to, but at least with C PETSc code an argument for the "strong scaling" case (where you work with global sizes and only choose the number of ranks at runtime) is that it allows you to write code which better hides the details of the implementation, be it sequential, parallel, or even some future implementation which doesn't nicely map to a set of local sizes.

**Comment by stevengj** [comment]
As much as possible, I think we should preserve the abstraction that a vector refers to the *whole* vector, not just to the local part.   For example, `length` should return the global length.  e.g. `sum(x) / length(x)` should be the mean, regardless of how `x` is distributed.

**Comment by JaredCrean2** [comment]
Those both sound like good reasons; let's leave things the way they are.
