### ISSUE TITLE
Missing MatShellGetContext

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaParallel/PETSc.jl#58]
For some reason the `MatShellGetContext` function is not wrapped.  The corresponding `*GetContext` functions for other petsc components are wrapped, as is `MatShellSetContext`, so I'm not sure why this is happening

**Comment by kshyatt** [comment]
Could it be the same issue I was having with `SNESSetFunction`? I think we need to point out explicitely to Clang where `petscconf.h` is.

**Comment by JaredCrean2** [comment]
Could be related.  I added the full path of `petscconf.h`to `clang_includes` but no change in the output.

**Comment by JaredCrean2** [comment]
Correction, many functions which previously were commented out due to undefined symbols are no longer commented out with this change.  No change to `MatShellGetContex` though.

**Comment by JaredCrean2** [comment]
Similarly, the `PetscCopyMode`enum is not picked up from `petscsys.h`.  It is not protected by any ifdefs, so I'm not sure why it did not get wrapped.  

Problems like this are really starting to impact my productivity, so I want to get this sorted out.  

CC: @ihnorton : I submitted a PR to Clang so the regular version of Clang can wrap Petsc.  Hopefully this will make it easier to find the problem.

**Comment by ihnorton** [comment]
> MatShellGetContex
> PetscCopyMode

These are both fixed by adding the path to the include directory under the build path to `clang_includes` so that Clang can find `petscconf.h`. e.g. `"../../deps/RealDouble/petsc-3.6.0/arch-darwin-c-debug/include"`.

If you want to see header errors, comment out the `run(wc)` at the end of your script. Then start Julia and do:
```
include("wrap_PETSc.jl")
wrap_c.parse_c_headers(wc)
```

**Comment by JaredCrean2** [comment]
I added on line 22 [here](https://github.com/JuliaParallel/PETSc.jl/blob/master/src/generated/wrap_PETSc.jl) but `MatShellGetContext` is not present in the PETSc.jl that it generates.  Was it present in the output of your test?

**Comment by ihnorton** [comment]
Yes. You have to add the directory, not the file. Those paths are where
clang looks to find the file when it sees #include "petscconf.h"

**Comment by ihnorton** [comment]
It's the same thing as adding paths with -I

**Comment by JaredCrean2** [comment]
That did it.  Much thanks.

**Comment by ihnorton** [comment]
Great, hopefully this should significantly decrease the gymnastics required in the rewriter.
