### ISSUE TITLE
Type Unstable Constructors

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaParallel/PETSc.jl#59]
I just noticed that several of the outer constructors for `Mat` are type unstable because they format of the matrix (`MType` is a type parameter of the object but an argument of the outer constructor.  This could be fixed by making them all inner constructor methods, but that seems like a misuse of inner constructors. Does anyone have any clever ideas on how to fix this?

**Comment by JaredCrean2** [comment]
Perhaps answering my own question, we could remove the matrix format as a type parameter.  We currently don't really use it for dispatch, but rather to generate error messages for illegal operations.  Maybe we should just use assertions instead?

**Comment by jiahao** [comment]
Could you provide an example? I had a quick look but it's not obvious to me.

**Comment by JaredCrean2** [comment]
Sure:
```julia
function Mat{T}(::Type{T}, mtype::C.MatType=C.MATSEQAIJ; comm::MPI.Comm=MPI.COMM_WORLD)
  p = Ref{C.Mat{T}}()
  chk(C.MatCreate(comm, p))
  Mat{T, mtype}(p[])  # mtype is an argument
end
```

**Comment by jiahao** [comment]
What does `@code_warntype` say?

**Comment by JaredCrean2** [comment]
It says the returned type can is `Any`.  
```julia
julia> @code_warntype Mat(Float64, PETSc.C.MATSEQAIJ)
Variables:
  #s46::Type{Float64}
  mtype::Symbol

Body:
  begin 
      $(Expr(:line, 31, symbol("/home/jared/.julia/v0.4/PETSc/src/mat.jl"), symbol("")))
      return (PETSc.__Mat#16__)(MPI.COMM_WORLD,#s46::Type{Float64},mtype::Symbol)::Any
  end::Any
```

PETSc.C.MATSEQAIJ is a `symbol` specifying the format the underlying matrix is stored in, but does not affect the format of the data that julia owns.

**Comment by JaredCrean2** [comment]
The `Mat{T, MType}` object uses the *value* of the `MType` symbol, not its datatype, as the static parameter, and because the value is not known at compile time, this function is not type stable.

**Comment by stevengj** [comment]
We could also just use `Val{:mtype}` for the `MType` argument, so that the matrix type is passed as a type.  (And perhaps declare some 'const' aliases for common types.)

**Comment by JaredCrean2** [comment]
Values types would solve the problem, but the other aspect of this is code generation.  We currently generate a lot of identical code for different matrix types (for example, the generated code for `setindex!` will be identical for all matrix types because PETSc handles dispatch internally.) I suppose that is one point in favor of removing the `MType` parameter, although I'm not really convinced that is a good idea either.

**Comment by JaredCrean2** [comment]
I looked over the Petsc API, and it doesn't provide enough access to the internal details of the matrices to make dispatching on their format useful.  I think removing the type parameter is the right answer here.

This has the potential to be breaking because it changes the inner constructor signature, but the outer constructors will be unchanged, so hopefully the impact will be minimal.
