### ISSUE TITLE
Add support for `nompi` version

### ISSUE THREAD

**Issue by tadeu** [JuliaParallel/PETSc.jl#67]
Hi,

How difficult/laborious would it be to support `nompi` version of PETSc, specially on Windows? Specially, to make the `MPI.jl` dependency optional, in this case?

Thanks!

**Comment by JaredCrean2** [comment]
Let's separate this into two pieces, Windows support and non-mpi support.  Non-mpi support is possible, although the Julia package manager does not (currently) have a good way to express an optional dependency.

Windows support is more involved.  When you say Windows, do you mean native Windows or cygwin?

**Comment by tadeu** [comment]
Ok, I've managed to make it work :).

About non-mpi support: the `master` version of `MPI.jl` is at least "importable" on Windows, so there's no problem with it when it won't be "effectively" used.

About Windows support: yes, building PETSc on Windows is something like an order of magnitude more complex than building it on Linux. I'm using a pre-compiled version, and I hardcoded the path to the DLL (see diff [here](https://github.com/JuliaParallel/PETSc.jl/issues/68#issuecomment-215087632)). It would be nice to have an official support for this. I thought about having pre-defined environment variables, e.g.:

```
set JULIA_PETSC_REAL_DOUBLE=D:\PETSc\real-double\PETSc.dll
set JULIA_PETSC_COMPLEX_DOUBLE=D:\PETSc\complex-double\PETSc.dll
```

Then `PETSc.jl` wouldn't try to build PETSc, but just use it, if those variables are defined.

**Comment by JaredCrean2** [comment]
Excellent.

Allowing users to point `Petsc.jl` at a different should definitely be supported, and if helps Windows support, that's even better.

**Comment by stevengj** [comment]
(In general, we will want precompiled binaries for both Mac and Windows.  This is the usual approach to `Pkg.build` for external dependencies, only compiling from source on non-Mac Unices.    Also, you could specify an alternative petsc build by an environment variable at `Pkg.build` time; I think I suggested this in another issue.)

**Comment by stevengj** [comment]
See #55

**Comment by JaredCrean2** [comment]
If MPI is importable and the build system now allows using an existing Petsc build, I think that is a sufficient solution for this?  If there are no objections I will close tomorrow.
