### ISSUE TITLE
rename KSPSolveTranspose! to Base.LinAlg.At_ldiv_B!

### ISSUE THREAD

**Issue by stevengj** [JuliaParallel/PETSc.jl#70]
When I wrote this function, I didn't realize that there was a "standard" name for this method buried in `Base.LinAlg`

**Comment by JaredCrean2** [comment]
I was wondering...
https://github.com/JuliaParallel/PETSc.jl/blob/master/src/ksp.jl#L124

Should that name be exported from Base?  `A_ldiv_B!` is.

**Comment by stevengj** [comment]
Seems like it.

**Comment by JaredCrean2** [comment]
I will open an issue

**Comment by JaredCrean2** [comment]
(btw, sent you an email about indexing and AbstractArrays)

**Comment by stevengj** [comment]
See also https://github.com/JuliaLang/IterativeSolvers.jl/issues/1#issuecomment-220054539

**Comment by stevengj** [comment]
See also JuliaLang/julia#16425.  (Jared, when you file related issues, be sure to add cross-references so that the github issues point to one another.)

**Comment by simonbyrne** [comment]
Done in #99.
