### ISSUE TITLE
Finalize MPI in petsc_com.jl

### ISSUE THREAD

**Issue by bhk37** [JuliaParallel/PETSc.jl#91]
Running PETSc.jl with mpirun gives the following MPI communication error:

> mpirun has exited due to process rank 0 with PID 82427 on
> node n0000.scs00 exiting improperly. There are two reasons this could occur:
> 
> 1. this process did not call "init" before exiting, but others in
> the job did. This can cause a job to hang indefinitely while it waits
> for all processes to call "init". By rule, if one process calls "init",
> then ALL processes must call "init" prior to termination.
> 
> 2. this process called "init", but exited without calling "finalize".
> By rule, all processes that call "init" MUST call "finalize" prior to
> exiting or it will be considered an "abnormal termination"
> 
> This may have caused other processes in the application to be
> terminated by signals sent by mpirun (as reported here).

I found this occurs because MPI is not properly finalized in PETSc.__init__(). A simple fix is to add MPI.Finalize() after line 34 in petsc_com.jl. Could this be changed in the master branch?

**Comment by stevengj** [comment]
I think that should be fine.  Can you submit a pull request?

**Comment by stevengj** [comment]
(Probably we only want to do this if Petsc initialized MPI itself, so we can set a flag to save whether we called `MPI.Init()`.)

**Comment by bhk37** [comment]
Good point. Pull request submitted.

**Comment by simonbyrne** [comment]
Should no longer be necessary with #99.
