### ISSUE TITLE
Beginner Question: Using Ubuntu 18.04 and julia 1.0.3 within visual studio

### ISSUE THREAD

**Issue by Chaztikov** [JuliaParallel/PETSc.jl#96]
Hi, I recently tried to add Petsc.jl from within visual studio, the output is below, I am admittedly very new to this, so I beg you for your mercy.

Thanks, (if there's a better place for this question, please let me know)
Charles

(v1.0) pkg> add https://github.com/JuliaParallel/PETSc.jl.git
   Cloning git-repo `https://github.com/JuliaParallel/PETSc.jl.git`
  Updating git-repo `https://github.com/JuliaParallel/PETSc.jl.git`
[ Info: Assigning UUID 01372b9a-f933-5704-bf84-c4fcbc0ed3e3 to PETSc
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ArrayViews [a5c3d3bf]:
 ArrayViews [a5c3d3bf] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0-0.4.12, 0.5.0, 0.6.0-0.6.4, 0.7.0] or uninstalled
 ├─restricted to versions 0.0.0-* by PETSc [01372b9a], leaving only versions [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0-0.4.12, 0.5.0, 0.6.0-0.6.4, 0.7.0]
 │ └─PETSc [01372b9a] log:
 │   ├─possible versions are: 0.0.0 or uninstalled
 │   └─PETSc [01372b9a] is fixed to version 0.0.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

(v1.0) pkg> add ArrayViews
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ArrayViews [a5c3d3bf]:
 ArrayViews [a5c3d3bf] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0-0.4.12, 0.5.0, 0.6.0-0.6.4, 0.7.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0-0.4.12, 0.5.0, 0.6.0-0.6.4, 0.7.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

(v1.0) pkg> update
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/floswald/ApproXD.jl`
  Updating git-repo `https://github.com/JuliaLang/openlibm`
  Updating git-repo `https://github.com/JuliaParallel/MPI.jl`
  Updating git-repo `https://github.com/omnisci/OmniSci.jl`
  Updating git-repo `https://github.com/FluxML/Flux.jl.git`
  Updating git-repo `https://github.com/korsbo/Latexify.jl`
  Updating git-repo `https://github.com/JuliaDiffEq/DifferentialEquations.jl`
  Updating git-repo `https://github.com/JuliaFEM/JuliaFEM.jl`
  Updating git-repo `https://github.com/JuliaFEM/FEMBase.jl`
  Updating git-repo `https://github.com/eschnett/SPH.jl.git`
  Updating git-repo `https://github.com/Paulms/HDiscontinuousGalerkin.jl.git`
  Updating git-repo `https://github.com/JuliaMatrices/BlockBandedMatrices.jl.git`
  Updating git-repo `https://github.com/Keno/Cxx.jl`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

(v1.0) pkg>

**Comment by stevengj** [comment]
This package hasn't been updated for Julia 1.0 yet.
